### ISSUE TITLE
Double slash appearing in URL

### ISSUE THREAD

**Issue by tekwon** [elpete/quick-tailwind-inertia#4]
![image](https://user-images.githubusercontent.com/12782268/103162959-a13feb80-484b-11eb-97ba-c7252318c7ea.png)

Any idea what may be causing this? Refreshing causes a new slash to be added to the URL. Running on Commandbox 5.2.1.

![image](https://user-images.githubusercontent.com/12782268/103162995-07c50980-484c-11eb-9e4d-f0c766b147c9.png)

**Comment by elpete** [comment]
This is a ColdBox bug that I'm attempting to solve here: https://github.com/ColdBox/coldbox-platform/pull/467
